name: alsignon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  package_info: ^2.0.0
  time_formatter: ^1.0.0+5
  fluttertoast: ^8.0.6
  http: ^0.12.1
  permission_handler: ^7.1.0
  app_settings: ^4.1.0
  cached_network_image: ^2.0.0-rc
  flutter_spinkit: ^5.0.0
  connectivity: ^3.0.4
  introduction_screen: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - lib/Assets/Languages/ar.json
   - lib/Assets/Languages/en.json
   - lib/Assets/image/cashpayment.png
   - lib/Assets/image/cardpayment.png
   - lib/Assets/image/img1.jpg
   - lib/Assets/image/img2.jpg
   - lib/Assets/image/img3.jpg
   - lib/Assets/image/mainlogo.png
   - lib/Assets/image/map_marker.png
   - lib/Assets/image/map_pin.png
   - lib/Assets/image/no_internet.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler1
      fonts:
        - asset: lib/Assets/Fonts/Cairo-Black.ttf
        - asset: lib/Assets/Fonts/Cairo-Bold.ttf
        - asset: lib/Assets/Fonts/Cairo-ExtraLight.ttf
        - asset: lib/Assets/Fonts/Cairo-Light.ttf
        - asset: lib/Assets/Fonts/Cairo-Regular.ttf
        - asset: lib/Assets/Fonts/Cairo-SemiBold.ttf
    - family: Schyler2
      fonts:
        - asset: lib/Assets/Fonts/Tajawal-Black.ttf
        - asset: lib/Assets/Fonts/Tajawal-Bold.ttf
        - asset: lib/Assets/Fonts/Tajawal-ExtraBold.ttf
        - asset: lib/Assets/Fonts/Tajawal-ExtraLight.ttf
        - asset: lib/Assets/Fonts/Tajawal-Medium.ttf
        - asset: lib/Assets/Fonts/Tajawal-Regular.ttf
        - asset: lib/Assets/Fonts/Tajawal-Light.ttf
    - family: Schyler
      fonts:
        - asset: lib/Assets/Fonts/Almarai-Bold.ttf
        - asset: lib/Assets/Fonts/Almarai-ExtraBold.ttf
        - asset: lib/Assets/Fonts/Almarai-Light.ttf
        - asset: lib/Assets/Fonts/Almarai-Regular.ttf
    - family: Schyler5
      fonts:
        - asset: lib/Assets/Fonts/Mada-Black.ttf
        - asset: lib/Assets/Fonts/Mada-Bold.ttf
        - asset: lib/Assets/Fonts/Mada-ExtraLight.ttf
        - asset: lib/Assets/Fonts/Mada-Light.ttf
        - asset: lib/Assets/Fonts/Mada-Medium.ttf
        - asset: lib/Assets/Fonts/Mada-Regular.ttf
        - asset: lib/Assets/Fonts/Mada-SemiBold.ttf
    - family: Schyler6
      fonts:
        - asset: lib/Assets/Fonts/ElMessiri-Bold.ttf
        - asset: lib/Assets/Fonts/ElMessiri-Medium.ttf
        - asset: lib/Assets/Fonts/ElMessiri-Regular.ttf
        - asset: lib/Assets/Fonts/ElMessiri-SemiBold.ttf
    - family: Schyler7
      fonts:
        - asset: lib/Assets/Fonts/Changa-Bold.ttf
        - asset: lib/Assets/Fonts/Changa-ExtraBold.ttf
        - asset: lib/Assets/Fonts/Changa-ExtraLight.ttf
        - asset: lib/Assets/Fonts/Changa-Light.ttf
        - asset: lib/Assets/Fonts/Changa-Medium.ttf
        - asset: lib/Assets/Fonts/Changa-Regular.ttf
        - asset: lib/Assets/Fonts/Changa-SemiBold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
